### ISSUE TITLE
postKeyboardInfo cannot be used in Objective-C projects

### ISSUE THREAD

**Issue by xhacker** [nixzhu/KeyboardMan#1]
Because `KeyboardInfo` is a Swift struct, which is not exposed to Objective-C world.

**Comment by xhacker** [comment]
I just realized `animateWhenKeyboardAppear` and `animateWhenKeyboardDisappear` are mostly sufficient.

**Comment by nixzhu** [comment]
Yes, they’re convenient closures. 

I write a blog for it. https://github.com/nixzhu/dev-blog/blob/master/2015-07-27-keyboard-man.md
