### ISSUE TITLE
postKeyboardInfo won’t get called when switch from emoji keyboard to English keyboard on iOS 9

### ISSUE THREAD

**Issue by xhacker** [nixzhu/KeyboardMan#2]
However, English keyboard is slightly shorter than emoji keyboard. Not sure if it’s an iOS 9 bug. I’m on iPhone 5s, iOS 9 beta 4.

**Comment by nixzhu** [comment]
In my test, English keyboard has the same height as Emoji keyboard (iPhone 5, iOS 9 beta 4).

But it’s a bug when change from Emoji Keyboard to Chinese Handwrite Keyboard will not postKeyboardInfo. Fixed in 0.3.1.

Thanks!

**Comment by xhacker** [comment]
Awesome, thank you!
