### ISSUE TITLE
有一个小BUG

### ISSUE THREAD

**Issue by maquannene** [nixzhu/KeyboardMan#4]
1.点击进入编辑。此时键盘在底部
2.长按键盘右下角键盘按键。点击 拆分键盘 （split）或者 浮动键盘（undock），此时键盘分成左右两半，在屏幕中间
3.点击键盘右下角键盘按键收起，出现编辑框没收起状况

**Comment by nixzhu** [comment]
感谢测试出此 Bug，已在版本 0.4 里修复。

**Comment by maquannene** [comment]
感谢及时修复。
另外还有一点，在键盘变为 浮动  或者 拆分，即只要不在底部时，编辑栏就会出现在底部。
如果特别严格要求的话，希望跟随键盘的表现是和 inputAccessoryView一致的。
不知道能不能达到这种要求。

**Comment by nixzhu** [comment]
我观察了，在浮动或拆分时，系统会发送键盘Hide通知，这适合于 KeyboardMan 的两个方便动画闭包。

如果你想自己控制你的输入框的位置，可使用 postKeyboardInfo 闭包来自行决定。比如你可以通过 frameEnd 来确定 Keyboard 的位置再做相关动画逻辑。
